name: papyrus-retrieval
channels:
  - pytorch
  #- nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  #- nvidia::cuda-toolkit=11.8
  - psycopg2=2.9.9
  #- pytorch::pytorch-cuda=11.8

  - pip:
      - alembic==1.13.2
      - celery[redis]==5.4.0
      - fastapi==0.111.0
      - pgvector==0.3.2
      - minio==7.2.8
      - pip==24.2
      - pre-commit==3.8.0
      - pylint==3.2.3
      - ruff==0.4.8
      - albumentations==1.4.14
      - opencv-python==4.10.0.84
      - sphinx==7.4.7
      - sphinx-rtd-theme==2.0.0
      - semver==3.0.2
      - hydra-core==1.3.2
      - litserve==0.2.2
      - huggingface-hub==0.25.2
      - torchvision==0.17.2
      - torch==2.2.2
      - numpy==1.26.4
      - sphinxcontrib-openapi==0.8.4
